# Site settings
title: Trung Le blog
email: 
# description: "A computer science enthusiast"
baseurl: ""
url: "http://lehgtrung.github.io"
# twitter_username: trungkak
github_username:  lehgtrung

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
