# Site settings
title: Trung Le blog
email: le.hg.trung@gmail.com
description: "We can only see a short distance ahead, but we can see plenty there that needs to be done. - Alan Turing"
baseurl: ""
url: "http://lehgtrung.github.io"
# twitter_username:
github_username:  lehgtrung

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
